Repository nordtheme/visual-studio-code, pull requests merged in 2018-06, with the labels that each got.

#71 Add underline to links in markdown
  themes/nord.json
Labels: context-syntax, scope-compatibility, status-accepted, type-improvement

#84 Replace Gulp with npm scripts
  .travis.yml
  circle.yml
  gulpfile.js
  package-lock.json
  package.json
Labels: context-workflow, scope-maintainability, type-improvement

#85 CI build configuration updates
  .circleci/config.yml
  .npmrc
  .travis.yml
  circle.yml
  yarn.lock
Labels: context-workflow, scope-maintainability, type-improvement

#86 Add Prettier
  .prettierignore
  package-lock.json
  package.json
  prettier.config.js
Labels: context-workflow, scope-compatibility, type-improvement
