Repository nordtheme/visual-studio-code, pull requests merged in 2019-03, with the labels that each got.

#91 Colors of Git status in file explorer
  README.md
  assets/scrot-feature-git-status-file-explorer.png
  themes/nord.json
Labels: context-ui, scope-ux, type-feature

#92 Coloring active line number
  README.md
  assets/scrot-feature-active-line-number.png
  themes/nord.json
Labels: context-ui, scope-ux, type-feature

#93 Editor hints
  README.md
  assets/scrot-feature-editor-hints.png
  themes/nord.json
Labels: context-ui, scope-ux, type-feature

#94 Tab top borders
  themes/nord.json
Labels: context-ui, scope-ux, type-feature

#96 New notification center UI
  README.md
  assets/scrcast-feature-notification-center.gif
  themes/nord.json
Labels: context-ui, scope-ux, type-feature

#110 Improve label font color of `view` quick panel
  themes/nord.json
Labels: context-ui, scope-ux, type-improvement

#104 fix: editor groups border can't be transparent
  themes/nord.json
Labels: context-ui, scope-stability, scope-ux, type-bug

#67 Make Perl sigils the same color as variables
  themes/nord.json
Labels: context-syntax, type-improvement

#115 Remove meta.var.expr from scope selector
  themes/nord.json
Labels: context-syntax, scope-ux, type-improvement

#112 Decrease opacity for peek view match highlighting
  themes/nord.json
Labels: context-ui, scope-ux, type-improvement

#113 Improve function parameter highlighting in Python
  themes/nord.json
Labels: context-syntax, scope-ux, type-improvement

#114 Improve interpolated string literals
  themes/nord.json
Labels: context-syntax, scope-compatibility, scope-ux, type-improvement

#116 Background color of inactive keyboard focused list items
  themes/nord.json
Labels: context-ui, scope-ux, type-feature

#118 Comment Color Brightness
  themes/nord.json
Labels: context-syntax, priority-high, scope-ux, type-improvement
