Repository nordtheme/visual-studio-code, pull requests merged in 2020-06, with the labels that each got.

#173 Adopt semantic highlighting
  themes/nord-color-theme.json
Labels: context-syntax, scope-compatibility, scope-quality, scope-ux, type-feature

#175 Activity Bar indicator styles
  themes/nord-color-theme.json
Labels: context-ui, scope-quality, type-feature

#177 Editor title border
  themes/nord-color-theme.json
Labels: context-ui, scope-compatibility, type-feature

#179 Minimap background, slider and Git state colors
  themes/nord-color-theme.json
Labels: context-ui, scope-quality, scope-ux, type-feature

#163 fix parentheses colors in js template strings
  themes/nord-color-theme.json
Labels: context-syntax, scope-compatibility, scope-quality, scope-ux, type-improvement
